# HTTP Methods

### Hello World

GET http://127.0.0.1:3030/hello/world HTTP/1.1

### Goodbye World

GET http://127.0.0.1:3030/goodbye/world HTTP/1.1

### Gimme Json

GET http://127.0.0.1:3030/gimme-json/0 HTTP/1.1

### Gimme Json

GET http://127.0.0.1:3030/gimme-json/0 HTTP/1.1

### POST

POST http://127.0.0.1:3030/send-entity HTTP/1.1
content-type: application/json

{
    "number": 42,
    "message": "Hello API."
}

### Fallback

GET http://127.0.0.1:3030/invalid HTTP/1.1


### Headers

### Get List Headers

GET http://127.0.0.1:3030/headers HTTP/1.1

### Get Header Value

GET http://127.0.0.1:3030/headers/auth HTTP/1.1
Authorization: Bearer token


### State Requests

### Post Entity

POST http://127.0.0.1:3030/state HTTP/1.1
content-type: application/json

{
    "number": 42,
    "message": "Hello API."
}

### Get Entity 13 

GET http://127.0.0.1:3030/state/42 HTTP/1.1

### Get all Entities

GET http://127.0.0.1:3030/state HTTP/1.1

### Delete Entity

DELETE http://127.0.0.1:3030/state/42 HTTP/1.1